global:
  scrape_interval: 5s #Collect metrics every 5 seconds

scrape_configs:
  - job_name: 'cadvisor' #Name of this metrics source
    static_configs:
      - targets: ['172.17.0.1:8080'] #Prometheus will pull metrics from cAdvisor
  
  - job_name: 'load-generator'
    static_configs:
      - targets: ['172.17.0.1:8000']